### ISSUE TITLE
Is it possible to use multiple profiles in use the same time

### ISSUE THREAD

**Issue by xypd** [ltworf/localslackirc#105]
I was hoping to use this gateway to host all of my slack profile in one client.

But it seems as if localslackirc only supports one token at a time. I can have more then one token in a file separated only by 1 space, but this doesn't allow me to have 4 profile working at the same time.

Is this possible?

Thanks

**Comment by daniel-Jones** [comment]
Localslackirc doesn't support more than one profile/workspace per process.

To run multiple slack profiles/workspaces you'll need to do the following:

1. have one token file per profile/workspace
2. run one instance of localslackirc per profile/workspace
3. use a different port for each instance

You can run localslackirc like this per profile/workspace:
``
./irc.py -p port -t /home/you/tokenfile1
``

**Comment by xypd** [comment]
Cool, so I would basically need to have say 4 terminal tabs open and run irc.py as you described in each of them.

Would be nice to be able to automate this. But this is a great start. thanks.

**Comment by daniel-Jones** [comment]
> Would be nice to be able to automate this. But this is a great start. thanks.

I suggest using tmux or screen so the process doesn't die when you close your terminal. This is how I start lsirc on login:

``
#!/bin/bash
BASE="$HOME/programming/python/localslackirc"
cd $BASE
tmux new-session -d -s slack -n lsirc
tmux new-window -t slack:1 -n irssi

tmux send-keys -t slack:0 "cd $BASE;python3 ./irc.py -j" C-m
sleep 1
tmux send-keys -t slack:1 "firejail irssi --home $HOME/.slackirssi -c 127.0.0.1 -p 9007" C-m
``

**Comment by xypd** [comment]
Wow, above and beyond. This is great.

Not sure if I want to go with another terminal at the moment (I'm an animal using the built in Mac OSX one ... lol)

But I think I can use what you gave me and make it work with my setup ... hopefully.

Cheers

**Comment by daniel-Jones** [comment]
tmux isn't another terminal, instead it is a multiplexer that allows you to attach and detach from sessions (allowing you to close your terminal and bring everything back later). The same goes for screen. https://github.com/tmux/tmux/wiki. It can be intimidating to learn and use, but I consider it worth the effort.

Happy to help with scripting things if you need assistance.

**Comment by xypd** [comment]
@daniel-Jones, thank you so much for your tips. I got everything working with pointing to multiple token files. I'll work on the screen multiplex (don't currently use homebrew) soon. But it's great to have an almost working lite slack/irc client again.

**Comment by xypd** [comment]
Hey @daniel-Jones, I'm gonna take you up on your offer to help with gnu screen.

I have one unrelated problem setup mostly working, but can't seem to get localslackirc working.

I currently have this in my .screenrc file:
`chdir ~/.localslackirc
screen -t python3 irc.py -p 9007 -t /Users/profile/.slack_tkn/rwv_tokens.txt`

Any ideas?
thanks

**Comment by xypd** [comment]
Thanks for the quick response. still not working, but can play with how you wrapped it.

**Comment by xypd** [comment]
Not sure why I can have the title be named, but it looks like this ended up being the code that worked. 

`screen -S python3 /Users/profile/.localslackirc/irc.py -p 9007 -t /Users/profile/.slack_tkn/rwv_tokens.txt`

I may fool around with it more as I get time. But this is working an good for now. 

The last goal it to get them to open into split windows automatically. Will need to research this more.

Thanks for your help @daniel-Jones, it got me over the hump yet again!

**Comment by xypd** [comment]
Just to finish off this with my final solution incase other Mac users land here.

I've put this in my /Users/yourprofile/.screenrc or create the text file with specific settings. Hit me up if you have any questions.


```
#enable the altscreen
# for example in vim, it allows to scroll with the mouse without
# "overflowing" on the terminal
# also it doesn't "pollute" the terminal when you quit vim
altscreen on

# automatically detach the session if the terminal is closed
autodetach on

# larger command history
defscrollback 10000

# set the encoding of the windows to utf-8
defutf8 on

# no welcome message
startup_message off

# allow to scroll
termcapinfo xterm* ti@:te@

# disable the annoying visual bell
vbell off

# mouse tracking allows to switch region focus by clicking
mousetrack on

# status bar
# %{= wk}: set the color to white on black
# %S: screen session name
# %-w: previous windows
# %{= kw}: set the color to black on white
# %n: current window number
# %t: current window title
# %{= wk}: set the color to white on black
# %+w: next windows
#caption always "%{= wk}%S: %-w%{= kw}%n %t%{= wk}%+w"
caption always "%S: %{= wk} %t"

# layouts
layout autosave on
sessionname Your-Slack-Session
split -v
screen -S python3 /Users/yourprofile/.localslackirc/irc.py -p 9001-yourport -t /Users/yourprofile/.yourslacktokenfolder/slack1_tokens.txt
title "1st_slack"
focus
screen -S python3 /Users/yourprofile/.localslackirc/irc.py -p 9002-yourport -t /Users/yourprofile/. yourslacktokenfolder/slack2_tokens.txt
title "2nd_Slack"
focus

shelltitle "cardamom"

# Add to .screenrc
#termcapinfo xterm* 'hs:ts=\E]0;:fs=\007:ds=\E]0;\007'
#defhstatus "screen ^E (^Et) | $USER@^EH"
#hardstatus off
```

**Comment by ltworf** [comment]
The version now in `master` (still not released) can run several instances using systemd and config files, rather than doing all this procedure manually.
