### ISSUE TITLE
Channel names with unicode

### ISSUE THREAD

**Issue by inariksit** [ltworf/localslackirc#108]
I tried to join a channel that contains an `ö`, this is what happens:
![](https://listenmaa.fi/b/localslackirc-channelname.png)

**Comment by ltworf** [comment]
Can you confirm? I can't reproduce…

**Comment by daniel-Jones** [comment]
can confirm similar situation when using the channel irssi opens. if i /list the channel I named "testö" it shows as "testo", I can connect to it and the user list shows correctly. However when I try to send a message to that specific channel I get this every time:

'''
Connecting to slack...
Connected to slack
Unknown command:  b'CAP LS'
Traceback (most recent call last):
  File "irc.py", line 515, in <module>
    main()
  File "irc.py", line 505, in main
    ircclient.command(i)
  File "irc.py", line 417, in command
    handlers[cmdid](cmd)
  File "irc.py", line 187, in _privmsghandler
    message
  File "/home/daniel_j/programming/python/localslackirc/slack.py", line 410, in send_message
    raise ResponseException(response)
slack.ResponseException: Response(ok=False, headers={'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '57', 'Connection': 'keep-alive', 'Date': 'Tue, 19 Feb 2019 13:03:24 GMT', 'Server': 'Apache', 'Expires': 'Mon, 26 Jul 1997 05:00:00 GMT', 'X-Content-Type-Options': 'nosniff', 'Pragma': 'no-cache', 'Vary': 'Accept-Encoding', 'X-Accepted-OAuth-Scopes': 'chat:write:user,client', 'X-OAuth-Scopes': 'identify,read,post,client,apps,admin', 'Cache-Control': 'private, no-cache, no-store, must-revalidate', 'X-XSS-Protection': '0', 'X-Slack-Req-Id': '62fb6e09-7558-4c75-857b-14dbbf8c17f9', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'Referrer-Policy': 'no-referrer', 'Content-Encoding': 'gzip', 'Access-Control-Allow-Origin': '*', 'X-Via': 'haproxy-www-m8ee', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 dc6d4687e92efc3664e6e66038fa3e6c.cloudfront.net (CloudFront)', 'X-Amz-Cf-Id': 'eNuIM4Y7AWgTxbgav5ub13NbPHkY49xUHlzsCq2-wWSI7p8Lwdincg=='})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "irc.py", line 519, in <module>
    traceback.print_last()
  File "/usr/lib/python3.7/traceback.py", line 173, in print_last
    raise ValueError("no last exception")
ValueError: no last exception
'''

I have no idea. (I assume none of this is sensitive...)

**Comment by ltworf** [comment]
If I remember correctly, you can't yet join from localslackirc

**Comment by inariksit** [comment]
@ltworf It works now when I join a channel named #kor instead of #kör! I didn't even try that last time :-P Thanks!

**Comment by ltworf** [comment]
It might be that they changed something on the server side…

**Comment by inariksit** [comment]
Oh well, it works anyway now! I'll close the issue.
