### ISSUE TITLE
Threading semi-invisible

### ISSUE THREAD

**Issue by luke-jr** [ltworf/localslackirc#117]
It appears that whether I see replies to a thread or not is random. Sometimes I see nothing. Sometimes I see the reply as if it was in the main chat.

**Comment by ltworf** [comment]
Are there exceptions printed in the console?

**Comment by luke-jr** [comment]
Probably. Lots of stuff printed. :/

**Comment by ltworf** [comment]
Well that stuff is probably important. If there are exceptions happening, it would help in understanding why some messages are getting skipped.

**Comment by abliss** [comment]
Guessing a bit here, but I think when a thread reply checks the box marked "Also post to channel", then the subtype becomes 'thread_broadcast' and i think the slack.py event loop doesn't have a handler for this subtype.

**Comment by ltworf** [comment]
Aren't all thread replies sent to the same channel as the original message?

**Comment by luke-jr** [comment]
No, usually thread replies are in a kind of "sub-channel" separate from the main chat. (Even when Slack had official IRC support, this was confusing because they just showed up in the main channel)

**Comment by abliss** [comment]
The behavior of the RTM api  actually seems backwards from that. If the user *doesn't* click the "also send to channel" button, then the RTM sends a normal Message with hiden=true, and then sends a second "thread_replied" event.

If the box *is* checked, the Message is *not* sent to the RTM; instead a thread_broadcast event is sent.

**Comment by ltworf** [comment]
So it should be enough to handle a thread_broadcast the same way as a message?

**Comment by abliss** [comment]
Yes, I think so.

**Comment by luke-jr** [comment]
IMO ideally threading would spawn a new ad-hoc channel, but admittedly that goes beyond simply fixing to adding functionality. ;)
