### ISSUE TITLE
 localslackirc: Doesn't show anything which I wrote via web interface

### ISSUE THREAD

**Issue by ltworf** [ltworf/localslackirc#118]
Reported on debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=926320

**Comment by ltworf** [comment]
slack doesn't seem to have any id for the messages at all, so there is no easy way to track that a received message is actually the same as a sent message.

On the other hand, rchat has ids that can be set from the client itself, so doing this for rchat seems trivial.

**Comment by daniel-Jones** [comment]
the timestamp is unique to the channel in slack and can serve as the id, "[...] and ts is the unique (per-channel) timestamp." from https://api.slack.com/events/message, https://twitter.com/slackapi/statuses/870268779510542336

**Comment by ltworf** [comment]
I tried, but seems that the timestamp that I get when sending the message is the timestamp of when slack gets the request, and when the message gets sent to the channel is the different timestamp of when that happens.

**Comment by ltworf** [comment]
Seems I was wrong… `event_ts` vs `ts`.

**Comment by ltworf** [comment]
https://github.com/ltworf/localslackirc/pull/119

**Comment by ltworf** [comment]
https://github.com/ltworf/localslackirc/pull/120

**Comment by ltworf** [comment]
It is partially done… private messages will show up weird.

**Comment by ltworf** [comment]
https://github.com/ltworf/localslackirc/pull/123
