### ISSUE TITLE
Display thread replies

### ISSUE THREAD

**Issue by abliss** [ltworf/localslackirc#128]
When people use the slack UI to thread their comments, they stop using the irc ettiquette of making it clear whom they're replying to, so the unthreaded irc channel gets hard to read. It would be neat to have some marker inserted that indicates which thread is being replied to.

**Comment by ltworf** [comment]
Do you have any suggestion on how to show this information without cluttering too much?

**Comment by abliss** [comment]
I'd describe the normal IRC ettiquette as approximately:
1. if replying to the most recent conversation, don't add anytihng.
2. if replying to a slightly older conversation, prepend the username you're replying to with a colon.
3. if replying to a much older conversation, prepend the name and a brief "re: topic" context.

This is hard to replicate exactly. I'm currently toying with a local hack that prepends `[rootUser@HH:MM] ` to all thread replies (with an extra `*` char if it's a thread_broadcast). It works okay for "short term threading", but won't work for channels with BBS-like multiday threads. Maybe if the previous post to the thread is older than some threshold, the server could prepend a snippet of the root text for context, and/or a link to view the thread in a browser?

**Comment by ltworf** [comment]
Who does multi day threads‽

**Comment by ltworf** [comment]
Would it be ok to just show and id of the thread and one can go look it up in the logs? :D

**Comment by ltworf** [comment]
Duplicates: #117
