### ISSUE TITLE
Synchronize last-read state across clients

### ISSUE THREAD

**Issue by abliss** [ltworf/localslackirc#129]
This is speculative, but I sometimes try to keep up with a slack instance both through localslackirc (on one machine, say) and also through another interface (irc, browser, or app). Slack has the Marked events that move the "you have read to here" status for each channel. It would be nifty to read/write these through localslackirc somehow.

I don't know much about the IRC spec, but one way might be to use a custom channelmode. E.g. intercept RTM api's `group_marked`, `im_marked`, and `channel_marked` events and surface them as an event of Channel Mode +M; and intercept the client command /mode +M and send it to the web api as the corresponding  `group.mark`, `im.mark`, or `channel.mark` command.

Then you would need to have an irc client that was aware of this custom mode/command and could interact with it. I'm experimenting locally with adding this support to circe. But maybe this is something that's already been contemplated by existing popular irc clients?

**Comment by ltworf** [comment]
My IRC client has a last read feature but afaik is local only.

What does +M do?

**Comment by abliss** [comment]
I just made up +M.  Like I said, i don't know the real IRC spec at all. I
looked at a list of channel modes and picked a letter that didn't seem to
be used already. Maybe there's a better way.

**Comment by ltworf** [comment]
I don't think this would work with actual clients. Feel free to reopen if you have an idea in practice.

My client doesn't even display channel modes at all for example.
