### ISSUE TITLE
cannot /msg a new user

### ISSUE THREAD

**Issue by abliss** [ltworf/localslackirc#131]
if I /msg a user that is not in any of my rooms, it does not succeed -- instead the console logs `Impossible to find user  b'foo'`. I think it's just checking in the local user cache. If it doesn't find the user in the cache, it should search for them by username.

**Comment by ltworf** [comment]
Do you know the RTM message for a new user?

**Comment by ltworf** [comment]
`user_change` is actually handled so I need to know if they are sending some other undocumented event for a new user.

**Comment by ltworf** [comment]
Ah well, seems the user doesn't care.

**Comment by abliss** [comment]
Sorry! I left that job and so I don't need to use slack anymore. :)

**Comment by ltworf** [comment]
I hope you moved to something less bad :D
