### ISSUE TITLE
Spammed by FileShared events

### ISSUE THREAD

**Issue by abliss** [ltworf/localslackirc#132]
It seems that sometimes (always?), when a user shares a file anywhere on my instance, I get a /msg about it in my client, which opens up a 1-1 channel with the sharer, even if they didn't share it with any rooms that I'm in.

**Comment by ltworf** [comment]
How does the RTM event look like?

**Comment by abliss** [comment]
```
{'type': 'file_shared', 'channel_id': 'CM0LRMSQM', 'file_id': 'FM06U0RD2', 'user_id': 'WFFRYBF2S', 'file': {'id': 'FM06U0RD2'}, 'event_ts': '1564765637.440300'}
sl_event:FileShared(file_id='FM06U0RD2', user_id='WFFRYBF2S', ts=0)
```

**Comment by ltworf** [comment]
The event only contains the fact that a file was shared, but not with whom. To retrieve it another call is performed, `files.info`, which will say where the file was shared.

Do you think you can get the information returned by that one?
