### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Hack5190** [ltworf/localslackirc#16]
Downloaded the localslackirc.zip to my ubuntu 4.4.0-112 machine running Python 3.5.2.  Unzipped to localslackirc. Created localslackcattoken file per the directions.  When running "./irc.py" in the localslackirc dir it returns:

Traceback (most recent call last):
  File "./irc.py", line 25, in <module>
    import slack
  File "/home/username/localslackirc/slack.py", line 55
     ok: bool
           ^
SyntaxError: invalid syntax

**Comment by ltworf** [comment]
Sorry, localslackirc uses the new NamedTuple syntax introduced in Python 3.6, so that is why Python 3.5 can't parse it.
