### ISSUE TITLE
Private channels can't be found.

### ISSUE THREAD

**Issue by florihupf** [ltworf/localslackirc#166]
Hi there,

Messages that were received via private channels were forwarded to my irc client as direct messages instead of a channel name.  After some investigation I found that the list of private channels were only found when querying them in a separate API call instead in one go, ie.:
```
    @lru_cache()
    def channels(self) -> List[Channel]:
        """
        Returns the list of slack channels
        """
        result: List[Channel] = []
        r = self.client.api_call("conversations.list", exclude_archived=True,
                types='public_channel,mpim', limit=1000)
        response = load(r, Response)
        if response.ok:
            a = load(r['channels'], List[Channel])
            r = self.client.api_call("conversations.list", exclude_archived=True,
                    types='private_channel', limit=1000)
            response = load(r, Response)
            if response.ok:
                b = load(r['channels'], List[Channel])
                a += b
            return a
        else:
            raise ResponseException(response)
```
Just posting for reference. HTH.

**Comment by ltworf** [comment]
Same as https://github.com/ltworf/localslackirc/issues/164

I'll leave this one since it has more details.

**Comment by tazjin** [comment]
How does one join private channels if setting up localslackirc while already being in them? It seems that `/join`-ing them doesn't work, but there's also no invites coming in.

**Comment by ltworf** [comment]
Please open another ticket, your support request is unrelated to this issue.
