### ISSUE TITLE
codec encoding crash

### ISSUE THREAD

**Issue by daniel-Jones** [ltworf/localslackirc#17]
```
Traceback (most recent call last):
  File "./irc.py", line 300, in <module>
    main()
  File "./irc.py", line 292, in main
    print(sl_event)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 55: ordinal not in range(128)
```

**Comment by ltworf** [comment]
Can this still happen?

I don't know how the code looked when you created the bug. Right not the type of sl_event is a union of namedtuple, seems weird that printing it would fail. However, not saying this is fixed.

**Comment by daniel-Jones** [comment]
Yeah still occurs. I've been assuming its my terminal because it happens often enough that others should have surely encountered it. I've just had that print statement commented out since.

I've not tried another terminal emulator to confirm this or not, I shall give that a go.

**Comment by ltworf** [comment]
can you replace the print with something like

```
try:
    print(variable)
except:
    print(repr(variable))
```

(replace variable with the actual variable :D

**Comment by ltworf** [comment]
And then post what it prints when it errors out? Then I could see what the issue is.

**Comment by daniel-Jones** [comment]
Afraid the output is no more helpful.

```
Traceback (most recent call last):
  File "./irc.py", line 421, in main
    print(sl_event)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0f3c' in position 84: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./irc.py", line 432, in <module>
    main()
  File "./irc.py", line 424, in main
    print(repr(sl_event))
UnicodeEncodeError: 'ascii' codec can't encode character '\u0f3c' in position 84: ordinal not in range(128)
```

**Comment by ltworf** [comment]
@AitorATuin do you have an idea on how to debug this?

I mean, besides removing the print and be done with it :D

**Comment by AitorATuin** [comment]
I will take a look at it tonight

**Comment by AitorATuin** [comment]
Since all the strings in python3 are unicode (32 bits) when `print` needs to show the string it tries to encode it to whatever the terminal is using. In the example is obviously ascii, so somehow some option is telling python to use ascii encoding for the output.

See those examples:

```
atuin ∘ leibniz ⊂ ⟨~⟩ ⊢ LC_ALL=C python3                                                               
Python 3.6.5
Type "help", "copyright", "credits" or "license" for more information.
>>> print("niñoñoño")
  File "<stdin>", line 0
    ^
SyntaxError: 'ascii' codec can't decode byte 0xe3 in position 7: ordinal not in range(128)
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>>
```

```
atuin ∘ leibniz ⊂ ⟨~⟩ ⊢ LC_ALL=en_US.UTF-8 python3                                                                                                                                
Python 3.6.5 
Type "help", "copyright", "credits" or "license" for more information.
>>> print("niñoñoño")
niñoñoño
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>>
```

@daniel-Jones how do you run the daemon? what environment?

**Comment by daniel-Jones** [comment]
Not really sure what would be useful, so I'll list off anything I can think of:
Parabola GNU+Linux-libre 4.18.3
Python 3.7.0
st (terminal, supports UTF8) same result in lxterminal
LC_ALL=C
$ locale charmap: ANSI_X3.4-1968
en_US.UTF-8 UTF-8, en_US ISO-8859-1 in /etc/locale (been generated)
Script to run lsirc:
```
#!/bin/bash
BASE="$HOME/programming/python/localslackirc"
cd $BASE
tmux new-session -d -s slack -n lsirc
tmux new-window -t slack:1 -n irssi

tmux send-keys -t slack:0 "cd $BASE;python3 ./irc.py -j" C-m
sleep 1
tmux send-keys -t slack:1 "irssi --home $HOME/.slackirssi -c 127.0.0.1 -p 9007" C-m
```
(Issue was also occurring back when I would run it with ```python3 ./irc.py -j``` manually.

The result of your first example is different locally (though LC_ALL is already C:
```
daniel_j@cirno[~]$ LC_ALL=C python3
Python 3.7.0 (default, Jul 15 2018, 10:44:58)
[GCC 8.1.1 20180531] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print("niñoñoño")
niñoñoño
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>> exit()
```
I don't really understand encoding and the desirable defaults. I would expect LC_ALLto be en_US or something similar.

**Comment by daniel-Jones** [comment]
Fixed by setting my locale to en_US.UTF-8. Closing.

There was talk in IRC about a patch disabling logging if the encoding is wrong, that'd be a preferable long-term solution. Probably deserves its own issue.
