### ISSUE TITLE
Authentication frequently expires

### ISSUE THREAD

**Issue by zdykstra** [ltworf/localslackirc#261]
I'm able to successfully use `localslackirc` with a small Slack instance that a few friends share. However, when using it with either of my $work instances, I'm forced to grab a new cookie quite frequently.  I also use Ripcord, and it does not have this issue when connecting. Their import process involves exporting a HAR file from Firefox and then importing it with Ripcord. 

https://cancel.fm/ripcord/static/app_misc/slack_har_howto_firefox_en-US.png

Is there some additional step I can take with `localslackirc` to avoid this problem?

**Comment by ltworf** [comment]
The har file is just the entire dump of the communication so it can grab whatever it wants from there.

Do you have any logs? Do you reuse the same token on several machines?

**Comment by zdykstra** [comment]
The following is logged before the docker container exits:

```
Traceback (most recent call last):
  File "/localslackirc/irc.py", line 873, in <module>
    main()
  File "/localslackirc/irc.py", line 848, in main
    asyncio.run(irc_listener())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/localslackirc/irc.py", line 820, in irc_listener
    await sl_client.login()
  File "/localslackirc/slack.py", line 359, in login
    self.login_info = await self.client.login(15)
  File "/localslackirc/slackclient/client.py", line 100, in login
    raise SlackLoginError(reply=login_data)
slackclient.exceptions.SlackLoginError: message=None reply={'ok': False, 'error': 'invalid_auth'}
```

I use Ripcord with the same imported HAR file on multiple machines, often concurrently. I imported the file roughly a year ago, and it's been working since. 

When I follow the steps at [wee-slack](https://github.com/wee-slack/wee-slack#get-a-session-tokenl) I get an `xoxs-` prefixed token. I was able to successfully use that without a cookie, though since I've just tried it I don't know for how long it will be valid.

**Comment by ltworf** [comment]
Could it be some security restriction added by the owner of your slack instance to reauthenticate often?

I have no idea how to reproduce this.

I am on 2 slack instances with xoxc and xoxs tokens and I haven't reauthenticated in a long long time.

Is it a public instance I could join to try?

**Comment by zdykstra** [comment]
It's unfortunately not a public instance. The only thing different with this slack instance is that it has two-factor authentication enabled. However, by simply using the token that the `wee-slack` method provides, my localslackirc instance has stayed connected for a little over 24 hours now. Using the `xoxc-` token along with a cookie, I could only stay connected for a few hours at a time.

Short of potentially bumping the documentation for how to get another token type, this issue appears to be largely solved for me now. Thank you for looking into this, and thank you for the great piece of software.

**Comment by ltworf** [comment]
Thanks. Can you point me to what method wee-slack uses?

I have no access to an instance with 2 factor authentication so I never tried that.

**Comment by zdykstra** [comment]
> Thanks. Can you point me to what method wee-slack uses?
> 
> I have no access to an instance with 2 factor authentication so I never tried that.

I used https://github.com/wee-slack/wee-slack#get-a-session-token - so far it seems to still be working.

**Comment by ltworf** [comment]
Are you still having the issue?

**Comment by zdykstra** [comment]
Using the token extracted by the wee-slack method seems to be working well. I haven't used localslackirc for a bit, but I was able to restart the Docker container and login to both of my Slack instances. localslackirc crashes after due to a nick parsing issue, but that seems to be unrelated to the lifetime of a token.
