### ISSUE TITLE
Document threading

### ISSUE THREAD

**Issue by balazser** [ltworf/localslackirc#262]
Hi @ltworf ,
is it possible to add some documentation for how threading happens in the slack gateway?
I'm wondering how can I differentiate threads and reply to them separately?

I use [irssi](https://irssi.org/) on Linux and I can see the following which is difficult to follow.
`15:59 <peter.ford> I say: Some random reply :eyes:`

**Comment by ltworf** [comment]
It's not supported. They are showed flattened within the conversation and you can't reply to them.

See https://github.com/ltworf/localslackirc/issues/117
