### ISSUE TITLE
Non-compliant line endings - should be CRLF

### ISSUE THREAD

**Issue by bobbimanners** [ltworf/localslackirc#268]
I noticed that `localslackirc` seems to transmit lines with just LF termination.  Most IRC clients can handle this, but RFC1459 says they should be CRLF.  This is causing me trouble with an IRC client running on the Apple II.

I modified `irc.py` around line 148 to add a `\r`.  This improves things, and doesn't seem to break other clients, although it doesn't completely resolve my issue.

Line changed by inserting `\r`:
       `self.s.write(b':%s %03d %s :%s\r\n' % (`

It is likely my irc client also has bugs.  Debugging is ongoing (this is new development on the Apple II side ...)

**Comment by ltworf** [comment]
You are indeed right.

Could you post a PR with your little change so I can easily test it with my client?

**Comment by bobbimanners** [comment]
PR done - hopefully I didn't mess it up ;)

All the best,
Bobbi

**Comment by ltworf** [comment]
https://github.com/ltworf/localslackirc/pull/270

Does it work now?

**Comment by ltworf** [comment]
Closing due to no response and PR merged.

**Comment by bobbimanners** [comment]
Seems to work for me :)

**Comment by ltworf** [comment]
Ah good :)
