### ISSUE TITLE
leading colon in IRC messages is removed before it arrives on slack

### ISSUE THREAD

**Issue by terceiro** [ltworf/localslackirc#277]
if I send e.g. `:rocket:` from IRC, the slack side only receives `rocket:`.

**Comment by ltworf** [comment]
A strange bug indeed!

I tried by using the HTML escape for `:` and slack skips the first occurrence anyway, and shows the HTML code for the 2nd one.

The plot thickens…

**Comment by ltworf** [comment]
```
{"type":"message","user":"xxx","client_msg_id":"xxx","suppress_notification":false,"text":":rocco:","team":"xxx","blocks":[{"type":"rich_text","block_id":"P\/xxx","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":":rocco:"}]}]}],"source_team":"xxx","user_team":"xxx","channel":"xxx","event_ts":"1616784484.000600","ts":"1616784484.000600"}
```

This is what I see sniffing the websocket, sending one such message from the browser.

It looks quite normal
