### ISSUE TITLE
please present "bot" as a proper user so I can ignore it

### ISSUE THREAD

**Issue by terceiro** [ltworf/localslackirc#294]
It's not fun to receive highlights when a bot notifies channels about stuff I am doing myself. :-)

**Comment by ltworf** [comment]
lol

So you did all the work to format the bot output to ignore it? :D :D

Anyway, so you want to use the bot name instead of the generic <bot> nickname, if I understand you correctly?

**Comment by ltworf** [comment]
@terceiro ping? Am I understanding the issue correctly?

**Comment by terceiro** [comment]
after thinking about it I think this issue makes no sense.

what I really wanted is not to be highlighted on bot messages that
reports on my own actions (gitlab MR, comments etc), but that's already
possible today.
