### ISSUE TITLE
dots in slack usernames need to be mapped to something else on IRC

### ISSUE THREAD

**Issue by terceiro** [ltworf/localslackirc#300]
The only non-alphanumeric characters allowed in IRC nicknames are "-",  "[", "]", "\", "`", "_", "^", "{", "|", "}". 

slack users that have dots in their usernames can cause issues in some IRC clientes. For example hexchat does not highight messages to you if your nickname contains a dot. Google told me Quassel [has issues as well](https://bugs.quassel-irc.org/issues/1408).

On the slack side, it says: "Usernames must be all lowercase. They cannot be longer than 21 characters and can only contain letters, numbers, periods, hyphens, and underscores." (i.e. `a-z0-9.-_`). Of those, only "." is invalid on the IRC side. I propose  to map "." in slack to one of "|", "^" or "\\" or "`" on IRC. I don'think any of those is good, but we need to pick one.

**Comment by ltworf** [comment]
Argh, literally everyone where I work has a . in the name, that's going to mess with my logs

**Comment by terceiro** [comment]
yeah, maybe we can come up with a better solution. maybe make the
mapping optional? or maybe don't do anything, and let clients be
reasonable and accept dots in nicknames?

TBH I tried fixing the highlighting in hexchat first, and only opened
this issue here after I couldn't do that quickly enough for my tast.

**Comment by ltworf** [comment]
My irc client (konversation) actually accepts it fine so I'm not so motivated about this.

**Comment by terceiro** [comment]
yeah in the end I made this work ok here. I think we don't even need to do this.
