### ISSUE TITLE
Filter NOUSERLIST by channel

### ISSUE THREAD

**Issue by dmulder** [ltworf/localslackirc#319]
The NOUSERLIST feature is useful, except I have some channels where I'd like it turned on, and others where I'd like it off.
For example, we have several company wide channels which blast me with a couple thousand user joined messages every time I load IRC. Meanwhile, I have small team channels where only a couple of users are present. It would be nice if NOUSERLIST where a per-channel option.

**Comment by ltworf** [comment]
To be honest, feel free to work on this. It's really not a priority for me.

**Comment by dmulder** [comment]
Not sure I have the time either, but maybe I'll take look later :)

**Comment by ltworf** [comment]
Ok, please close this if you do not intend to work on it.
