### ISSUE TITLE
slackbot messages are not displayed

### ISSUE THREAD

**Issue by daniel-Jones** [ltworf/localslackirc#4]
for example with a custom slackbot response. (to set one: workspace dropdown->customize slack->slackbot)

```
{'text': 'response text here', 'type': 'message', 'subtype': 'slackbot_response', 'user': 'USLACKBOT', 'channel': 'CAADVRQ6B', 'event_ts': '1524183094.000230', 'ts': '1524183094.000230'}
```

**Comment by ltworf** [comment]
Seems that slackbot is a fake user, but can also send messages as regular user (those work).

**Comment by ltworf** [comment]
How can I trigger that? My subtype is `bot_message`.
