### ISSUE TITLE
Pull request #35 (Don't include disabled user in /names) crashes on channels w/large # of users.

### ISSUE THREAD

**Issue by Hack5190** [ltworf/localslackirc#40]
The change to slack.py (line 158) and irc.py (lines 78-80) cause a crash when loading users in channels with large number of users.  Verified this w/2 channels of 1001 and 799 users.  The error is

`File "/home/bouncer/.local/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/users.info (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1a34c61dd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))`

**Comment by usercz** [comment]
Are you sure that's not a network issue?

It might be that they block clients after a certain number of requests.

**Comment by Hack5190** [comment]
Unlikely since it works without these changes to slack.py and irc.py (same channels, same number of users).
