### ISSUE TITLE
referenced channels show their id

### ISSUE THREAD

**Issue by daniel-Jones** [ltworf/localslackirc#42]
<#C03UGEJ38|general> should appear as just #general

**Comment by Hack5190** [comment]
Is this the same issue as #6?

**Comment by daniel-Jones** [comment]
it indeed is. the title of that issue didn't exactly scream relevant when initially making this, closing.

cheers!

**Comment by Hack5190** [comment]
I think #6 should have been closed ;)

**Comment by ltworf** [comment]
Sorry about this… I didn't think my project was going to have other users besides me :D
