### ISSUE TITLE
Simplify end user installation

### ISSUE THREAD

**Issue by rbarrois** [ltworf/localslackirc#44]
The current deployment process is good for hackers; if we want wider adoption, we'll have to stick to "standard" deployment best practices.

Ideas:
- Publish on PyPI (needs a ``setup.py``, clean dependencies, etc.);
- Push tags when a new version has been tested;
- Provide a docker image (ideally: automatically built on every tag push).

I can help with the Python packaging part; what is your opinion about versioning? Docker?

**Comment by xypd** [comment]
I'm not sure it's clear as to what this means ..."Place the token inside '~/.localslackirc'".

After you copy the token, do you past it into a text file? What do you name that file? Or does it it go into the mypy.conf? Or the requirement.txt file?

Perhaps it just me, but I would suggest elaborating further with this section of the read me. I'm stuck here and would image others could be too.

As far as docker I don't currently use it. I also am not keen on using it just for this one use. Though it's a good idea for those that already have it.

**Comment by daniel-Jones** [comment]
@xypd It isn't really clear what it means to someone not experienced, sorry about that.

Assuming you're using a Linux based system your token goes inside a text file named .localslackirc inside your home directory (/home/yourusername/). Alternatively you can call irc.py with the argument -t and pass it the location of your token file if you prefer to store it elsewhere ("./irc.py -t /home/yourname/slack/token.txt" for example)

**Comment by xypd** [comment]
getting an error when running python3 /Users/username/localslackirc/irc.py -t /Users/username/.slack_tkn/.tokens.txt

```
$ python3 irc.py
Traceback (most recent call last):
  File "irc.py", line 28, in <module>
    import slack
  File "/Users/username/localslackirc-dir/slack.py", line 24, in <module>
    from slackclient import SlackClient
  File "/Users/username/localslackirc-dir/slackclient/__init__.py", line 1, in <module>
    from .client import SlackClient
  File "/Users/username/localslackirc-dir/slackclient/client.py", line 28, in <module>
    from .server import Server
  File "/Users/username/localslackirc-dir/slackclient/server.py", line 25, in <module>
    from .slackrequest import SlackRequest
  File "/Users/username/localslackirc-dir/slackclient/slackrequest.py", line 27, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by daniel-Jones** [comment]
@xypd the localslackirc directory can be anywhere and named anything, that doesn't matter. You should put your slack token in the file "/Users/yourname/.localslackirc" (note that the file starts with a . and has no ending extension.

Alternatively the command you used ("python3 /Users/username/localslackirc/irc.py -t /Users/username/.slack_tkn/.tokens.txt") should work fine.

To fix the error you're getting you need to install requests. Try "pip install --user requests"

**Comment by xypd** [comment]
@daniel-Jones Thanks for your detailed follow up. Just before your post I managed to make some progress. Came to the same conclusion that you where suggesting. So I had already installed the modules in the requirement file "requests, six, typedload, websocket-client".

So my new error looks to be about certificate verify failed. Looking into ssl cert.

Feels like it's so close :D

```
$ python3 irc.py
{'ok': True, 'url': 'wss://cerberus-xxxx.lb.slack-msgs.com/websocket/token_seems_longer+then_what_mine_is’, 'team': {'id': 'ZZZ789012', 'name': 'Some Team', 'domain': 'someteam'}, 'self': {'id': 'XXX123456', 'name': 'your name'}}
Failed RTM connect
Traceback (most recent call last):
  File "/Users/username/localslackirc/slackclient/server.py", line 156, in connect_slack_websocket
    http_proxy_auth=proxy_auth)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websocket/_core.py", line 494, in create_connection
    websock.connect(url, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websocket/_core.py", line 217, in connect
    options.pop('socket', None))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websocket/_http.py", line 232, in _wrap_sni_socket
    server_hostname=hostname,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/username/localslackirc/slackclient/client.py", line 67, in rtm_connect
    self.server.rtm_connect()
  File "/Users/username/localslackirc/slackclient/server.py", line 131, in rtm_connect
    self.connect_slack_websocket(self.ws_url)
  File "/Users/username/localslackirc/slackclient/server.py", line 163, in connect_slack_websocket
    raise SlackConnectionError(message=str(e))
slackclient.exceptions.SlackConnectionError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)
Traceback (most recent call last):
  File "irc.py", line 402, in <module>
    main()
  File "irc.py", line 381, in main
    sl_event = next(sl_events)
StopIteration
```

**Comment by daniel-Jones** [comment]
Not able to really assist with this issue, unfortunately the only "solutions" that may help require not validating SSL certs and that's not something I'd ever instruct someone to do. 

Maybe one of the other lads subscribed to this issue could be of help?

**Comment by xypd** [comment]
No problem Thanks for the input and help you have provide so far. Cheers

**Comment by ReimarBauer** [comment]
> There is now a docker file, though I don't use docker and I don't really care for it.
> 
> I can make a setup.py, and .deb packages.
> 
> After this is done, maybe I can tag the 1st release…

I am happy with the docker file. Thx, worked perfectly.  

Based on the release tag I can add a package to conda-forge and we can switch later to the pypi version for the installation/setup.py procedure. conda-forge initial version will be based on the requirements file.

**Comment by ltworf** [comment]
@AitorATuin help? I have no idea what this means :D

**Comment by AitorATuin** [comment]
This is first time i hear about [conda](https://conda.io/en/latest/) :)

`Package, dependency and environment management for any language—Python, R, Ruby, Lua, Scala, Java, JavaScript, C/ C++, FORTRAN`

I guess he means to add packages for that package system as well.

I'm not a big fan of external package systems so i don't think they should supported by upstream developers. I think that providing a `setup.py` and an updated docker container is good enough.
Packagers can always use the `setup.py` to prepare packages for whatever distro or package system they want.

Maybe a pypi package makes sense since it's very common in python.

@ltworf if you provide tags we can have an updated docker repository in docker hub so it's not needed to clone the repo to use it.

**Comment by ltworf** [comment]
Tags for releases? They should be there already…

**Comment by ltworf** [comment]
I hope it is simplified enough now.
