### ISSUE TITLE
exception on ratelimiting

### ISSUE THREAD

**Issue by jiribohac** [ltworf/localslackirc#440]
We're a large organisation with lots of users and slack channels. In teh past year I've been having problems with localslackirc crashing when it got a ratelimit reply from slack.
I believe this is not handled as it should. https://api.slack.com/docs/rate-limits

However, I found a workaround. A colleague uses wee-slack and had the same problem, which got fixed by this weeslack commit, only fetching the channels the user is part of:
https://github.com/wee-slack/wee-slack/commit/d6a6dd9b9886fcaaeb8cd78c0c7105c3bd2ebebf

I modified this for localslackirc and it fixes my problems with ratelimiting - patch attached: 
[only-fetch-users-channels.patch.txt](https://github.com/ltworf/localslackirc/files/13317897/only-fetch-users-channels.patch.txt)

I think ratelimiting should be fixed properly, but this might be another useful improvement even if we had a proper fix.

**Comment by ltworf** [comment]
Can you try with this? https://github.com/ltworf/localslackirc/pull/441

The patch you sent has the side effect of showing only the channels one has already joined when doing /list in IRC, which makes that not so useful.

Of course I expect /list doesn't work for you in any case.

**Comment by jiribohac** [comment]
Your patch (#441) does not work for me. I get this:
```
Connecting to slack...
No last known timestamp. Unable to fetch history
Connected to slack
Closing connections
Cancelling running tasks
Traceback (most recent call last):
  File "/localslackirc/localslackirc", line 24, in <module>
    main()
  File "/localslackirc/irc.py", line 1088, in main
    asyncio.run(restart_listener_loop())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/localslackirc/irc.py", line 1084, in restart_listener_loop
    await irc_listener()
  File "/localslackirc/irc.py", line 1058, in irc_listener
    await asyncio.gather(
  File "/localslackirc/irc.py", line 1097, in from_irc
    await ircclient.command(cmd.strip())
  File "/localslackirc/irc.py", line 847, in command
    await handlers[cmdid](cmd)
  File "/localslackirc/irc.py", line 183, in _userhandler
    for sl_chan in await self.sl_client.channels():
  File "/localslackirc/slack.py", line 617, in channels
    r = await self.client.api_call(
  File "/localslackirc/slackclient/client.py", line 168, in api_call
    response_json = response.json()
  File "/localslackirc/slackclient/http.py", line 74, in json
    return json.loads(self.data)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

You're right, with my patch /list only shows the already joined channels.

**Comment by ltworf** [comment]
Another attempt?

I force pushed a different fix on the same branch.

**Comment by jiribohac** [comment]
> Another attempt?
> 
> I force pushed a different fix on the same branch.

This seems to work fine, thank you!
Except the behaviour of /list is strange:
I do "/list -YES" (in irssi). I immediately get "End of LIST" and then, two minutes later, I get the huge list of channels.
But I can't really verify if it's caused by these patches, because without them, localslackirc does not work for me at all. And I never used /list before, so I don't know how it used to work before the ratelimitting problem appeared.

**Comment by ltworf** [comment]
The code to send the list is very sequential, just sending the beginning, a for-loop and the send for the end.

The /list command seems to work for me, perhaps I'm doing something that isn't respecting the irc protocol though.

Anyway I won't investigate that unless it becomes a real problem.
