### ISSUE TITLE
posted images appear as edited

### ISSUE THREAD

**Issue by daniel-Jones** [ltworf/localslackirc#5]
[edited] prepended to messages with an image link regardless if they were or not, with or without text along with the image link.

**Comment by ltworf** [comment]
Yeah I know, for some reason slack generates an edited event for them. Also happens to links.

This is going to be hard to fix (unless I decide to just drop the [edited] feature). And I guess that's why they weren't shown in the slack gateway.

**Comment by daniel-Jones** [comment]
i wouldn't be opposed to dropping the edit feature, that way it's more true to the Slack gateway (though it's definitely not a problem to have it).
