### ISSUE TITLE
private irc /query switches to other users

### ISSUE THREAD

**Issue by knorrie** [ltworf/localslackirc#78]
I did `/query foo` and later if another slack user talks to me that window is reused and it's displayed as nick change:

```
-!- Irssi: Starting query in MendixSlack with foo
<Knorrie> blub
<foo> blab
Day changed to 03 Aug 2018
-!- foo is now known as bar
<bar> hey Knorrie, flapdiefloep!
<Knorrie> yes
-!- bar is now known as quux
<quux> another message
```

I'd expect it to open a new window in irssi, and not change an existing one with a different user.

**Comment by ltworf** [comment]
On konversation I do get a new window per private conversation.

**Comment by ltworf** [comment]
Can anyone else confirm this?

**Comment by knorrie** [comment]
I started happening at some point. Also, irssi does not see any members in channels any more:

[#foo] /n
22:35 [Users #foo]
22:35 -!- Irssi: #foo: Total of 0 nicks [0 ops, 0 halfops, 0 voices, 0 normal]

My local clone runs from the master branch back at f4ecc2f8bb. I have seen nicks in channels earlier, so I'll try going back and forward to see where it started happening.

**Comment by knorrie** [comment]
Updating to later code fixed this. I think it's the changes related to join events that did it.

When reconnecting, I still need to /cycle all channels to get then populated again.
