### ISSUE TITLE
Ignore messages from channels that are not joined

### ISSUE THREAD

**Issue by knorrie** [ltworf/localslackirc#80]
I'd like to not have all slack channels that I can see in the browser client also as channels in irc. I only choose a few important ones and all the rest should not distract me.

However, all messages from all other channels that I don't join via IRC end up in irssi window 1 now.

```
10:26 [lsi] < foo:#general> look at my new cat pics!!~``1
10:26 [lsi] < bar:#general> ice cream in the canteen!!
10:27 [lsi] < baz:#general> w00tw00t
10:28 [lsi] < whaa:#random> blahblahblahb
```

Just ignore them, so that the irssi status window is status window again.

**Comment by ltworf** [comment]
Probably happens because I use it with -j at all times.
