### ISSUE TITLE
Sent links are garbled

### ISSUE THREAD

**Issue by knorrie** [ltworf/localslackirc#81]
When I sent this to someone else:
```
http://10.140.10.25/~knorrie/blah
```

It ends up in slack as
```
http://10.140.10.25/~@Knorrie/blah
```

**Comment by daniel-Jones** [comment]
should be fixed as of https://github.com/ltworf/localslackirc/commit/1ff1b5674192ebe55193307ca4a3cdacb4e89e17

**Comment by ltworf** [comment]
Hehe this happened to me now, because someone was called "github"
